# Generated by Django 5.1 on 2024-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experiment_experiments_start_d_5ecae7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participantexperiment',
            index=models.Index(fields=['experiment_id'], name='participant_experim_e4d314_idx'),
        ),
    ]
